### ISSUE TITLE
Which IMU is on Val?

### ISSUE THREAD

**Issue by mauricefallon** [NASA-JSC-Robotics/valkyrie#10]
@MathisFrankB : Is this the IMU used on Val?
http://www.microstrain.com/inertial/3dm-gx4-25

And do you use this driver?
https://github.com/NASA-JSC-Robotics/imu_3dm_gx4_15

Does the RS232 and USB behave differently? Or is it fine to do for the USB version

**Comment by MathisFrankB** [comment]
The imu on val is the 3dm-gx4-15:
http://www.microstrain.com/inertial/3dm-gx4-15

You are correct about the driver being used.

The difference between the usb and the RS232 is in the com side of the imu. For using the RS232 the baud rate must be specified. Additionally we will run through the RS232 interface through a turbodriver and then that will use robonet to move data to the computer.

When the usb is plugged into the usb it creates a virtual serial port inside the computer to expose the data (which is why a baud rate must be specified). We want to move away from this since it requires the computer ports to interrupt which limits the number of imus that can be used.
