### ISSUE TITLE
Vicon marker mounting locations on Val

### ISSUE THREAD

**Issue by mauricefallon** [NASA-JSC-Robotics/valkyrie#27]
As mentioned on slack, @jlack1987 : could you give the x,y,z positions of the illustrated M6 threaded holes? We want to mount Vicon markers precisely.

![2016-04-22 16 19 35-edit](https://cloud.githubusercontent.com/assets/6404227/14766667/e37070da-0a0a-11e6-9f3a-ed21c36fa6f6.jpg)

I'm making an issue because we will come back to this for the torso and hands.

**Comment by ruckusrobotics** [comment]
Yeah sure thing. We are in Boston this week setting up the MIT bot, but when I get back i'll get you the location to these holes.

**Comment by jlack1987** [comment]
Yeah sure thing. We're in Boston this week setting up the MIT bot, but i'll get you the coords of these holes when I get back.

**Comment by jlack1987** [comment]
Here is the same image with the cartesian position of those points marked. I marked the two on the pelvis bone on the robots right side, but didn't mark the left because they are just mirrored, so you can just negate the y-component of the ones on the left to get the ones on the right. Let me know if ya need any more!

![pelvis_mounting_points](https://cloud.githubusercontent.com/assets/6334699/14961819/5a6355ca-1061-11e6-9625-0606cba5996f.png)

**Comment by christian-rauch** [comment]
We now would like to track the left hand pose with the Vicon system and intent to attach markers to the threaded M3 holes that hold the back plate.
![left_hand_plate_m3_screw_location](https://cloud.githubusercontent.com/assets/8226248/16918045/f811ec9c-4cfb-11e6-8402-26db88a0ad47.png)
@jlack1987 can you provide use with the 3D positions of these screws with respect to the "**leftPalm**" frame?

**Comment by jlack1987** [comment]
![valpalmphoto_annotated](https://cloud.githubusercontent.com/assets/6334699/16957759/567002a4-4da3-11e6-9508-389d2566977f.png)

Here ya go. Note that I flipped the image over.
